image: nirsnappy/build-serverless

before_script:
  -  npm i -g yarn

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - yarn
    - yarn build
    - yarn deploy
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'

    